### ISSUE TITLE
Can't add any hand in the range builder

### ISSUE THREAD

**Issue by Fredo2024** [lukebhan/memorizePreFlop#4]
I downloaded memorize preflop, but in the Range Builder, I cannot add any raise (or call for that matter) hands. if I load a preset range, only modification I can do is to remove hands, can't add or re-add any. (I am running on Windows). Is this a known issue? Thanks

Frederic

**Comment by Fredo2024** [comment]
I figured this one out, I simply had to move the slider above 0 to add the raises, duh.

However now I am running into another issue; when I do the hand trainer, the 2 cards aren't showing on the screen, Any help?

**Comment by lukebhan** [comment]
Hi, 
When you downloaded the memorize preflop folder and extracted it, there is a folder in there titled "cardimages". Move that folder to wherever the application file sits on your computer and the card images should populate as expected.
